Week5/class/proiect/api/urls.py
from django.urls import path, include
from rest_framework import routers
from api import views

router = routers.DefaultRouter()
router.register("location", views.LocationViewSet)

urlpatterns = [path("", include(router.urls))]

Week5/class/proiect/aplicatie1/urls.py
from django.urls import path
from aplicatie1 import views

app_name = "locations"

urlpatterns = [
    path("", views.LocationView.as_view(), name="lista_locatii"),
    path("adaugare/", views.CreateLocationView.as_view(), name="adauga"),
    path("<int:pk>/update/", views.UpdateLocationView.as_view(), name="modifica"),
    path("<int:pk>/sterge/", views.delete_location, name="sterge"),
    path("<int:pk>/dezactiveaza", views.deactivate_location, name="dezactiveaza"),
    path("<int:pk>/activeaza/", views.activate_location, name="activeaza"),
    #
    path("companies/", views.CompanyView.as_view(), name="list_companies"),
    path("company/add", views.CreateCompanyView.as_view(), name="add_company"),
    path(
        "company/<int:pk>/update/",
        views.UpdateCompanyView.as_view(),
        name="update_company",
    ),
    path("company/<int:pk>/sterge/", views.delete_company, name="delete_company"),
    path(
        "company/<int:pk>/dezactiveaza",
        views.deactivate_company,
        name="deactivate_company",
    ),
    path(
        "company/<int:pk>/activeaza/", views.activate_company, name="activate_company"
    ),
]

Week5/class/proiect/proiect/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("locations/", include("aplicatie1.urls")),
    path("", include("django.contrib.auth.urls"), {"next_page": "/"}, name="login"),
    path("", LoginView.as_view(template_name="registration/login.html"), name="login"),
    path("profile/", include("user_profile.urls")),
    path("api/", include("api.urls")),
]

Week5/class/proiect/user_profile/urls.py
from django.urls import path
from user_profile import views

app_name = "userprofile"

urlpatterns = [
    path("start_timesheet/", views.new_timesheet, name="start_pontaj"),
    path("end_timesheet/", views.stop_timesheet, name="stop_pontaj"),
]

Week5/class/proiect/templates/base.html
<html>
<head>
    {% block title %}
    {% endblock %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
</head>
<body>
<div class="container px-5 my-3">
    <div class="row">
        <div class="col-md-12">
            <nav>
                <a class="btn" href="/admin">Admin</a>
                {% if ready_to_work is False %}
                    <a href="{% url 'userprofile:stop_pontaj' %}" class="btn btn-danger">Oprire pontaj</a>
                {% else %}
                    <a href="{% url 'userprofile:start_pontaj' %}" class="btn btn-success">Pornire pontaj</a>
                {% endif %}
                {% if request.user.is_authenticated %}
                    <a class="btn btn-primary" href="{% url 'locations:lista_locatii' %}">Locatii</a>
                    <a class="btn btn-primary" href="{% url 'locations:list_companies' %}">Companii</a>
                    <a class="btn" href="{% url 'logout' %}">Logout</a>
                {% endif %}
            </nav>
        </div>
    </div>
</div>
{% block content %}
{% endblock %}
</body>
</html>