Week5/class/proiect/api/urls.py
from django.urls import path, include
from rest_framework import routers
from api import views

router = routers.DefaultRouter()
router.register("location", views.LocationViewSet)

urlpatterns = [path("", include(router.urls))]

Week5/class/proiect/aplicatie1/urls.py
from django.urls import path
from aplicatie1 import views

app_name = "locations"

urlpatterns = [
    path("", views.LocationView.as_view(), name="lista_locatii"),
    path("adaugare/", views.CreateLocationView.as_view(), name="adauga"),
    path("<int:pk>/update/", views.UpdateLocationView.as_view(), name="modifica"),
    path("<int:pk>/sterge/", views.delete_location, name="sterge"),
    path("<int:pk>/dezactiveaza", views.deactivate_location, name="dezactiveaza"),
    path("<int:pk>/activeaza/", views.activate_location, name="activeaza"),
    #
    path("companies/", views.CompanyView.as_view(), name="list_companies"),
    path("company/add", views.CreateCompanyView.as_view(), name="add_company"),
    path(
        "company/<int:pk>/update/",
        views.UpdateCompanyView.as_view(),
        name="update_company",
    ),
    path("company/<int:pk>/sterge/", views.delete_company, name="delete_company"),
    path(
        "company/<int:pk>/dezactiveaza",
        views.deactivate_company,
        name="deactivate_company",
    ),
    path(
        "company/<int:pk>/activeaza/", views.activate_company, name="activate_company"
    ),
]

Week5/class/proiect/proiect/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("locations/", include("aplicatie1.urls")),
    path("", include("django.contrib.auth.urls"), {"next_page": "/"}, name="login"),
    path("", LoginView.as_view(template_name="registration/login.html"), name="login"),
    path("profile/", include("user_profile.urls")),
    path("api/", include("api.urls")),
]

Week5/class/proiect/aplicatie1/models.py
from django.db import models


# Create your models here.
class Location(models.Model):
    city = models.CharField(max_length=100)
    country = models.CharField(max_length=90)
    active = models.BooleanField(default=1)

    def __str__(self):
        return f"{self.country} -> {self.city}"


class AuditLocation(models.Model):
    city = models.CharField(max_length=100)
    country = models.CharField(max_length=90)
    active = models.BooleanField(default=1)
    location = models.IntegerField()
    user = models.ForeignKey("auth.User", on_delete=models.CASCADE, default=1)

    def __str__(self):
        return f"{self.country} -> {self.city}"


class Company(models.Model):
    name = models.CharField(max_length=100)
    website = models.CharField(max_length=100)
    location = models.ForeignKey(Location, on_delete=models.CASCADE)
    active = models.BooleanField(default=1)

    def __str__(self):
        return f"{self.name} -> {self.website}"


class AuditCompany(models.Model):
    name = models.CharField(max_length=100)
    website = models.CharField(max_length=100)
    location = models.ForeignKey(Location, on_delete=models.CASCADE)
    active = models.BooleanField(default=1)
    company = models.IntegerField()
    user = models.ForeignKey("auth.User", on_delete=models.CASCADE, default=1)

    def __str__(self):
        return f"{self.name} -> {self.website}"

Week5/class/proiect/aplicatie1/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import ListView, CreateView, UpdateView
from aplicatie1.models import Location, AuditLocation, Company, AuditCompany


# Create your views here.
class LocationView(LoginRequiredMixin, ListView):
    model = Location
    template_name = "aplicatie1/locations_index.html"
    paginate_by = 5
    queryset = model.objects.all().order_by("id")

    def get_context_data(self, *args, **kwargs):
        data = super().get_context_data()
        data["page"] = (
            self.request.GET.get("page") if self.request.GET.get("page") else 1
        )
        return data


class CreateLocationView(LoginRequiredMixin, CreateView):
    model = Location
    fields = ["city", "country"]
    template_name = "aplicatie1/locations_form.html"

    def get_success_url(self):
        return reverse("locations:lista_locatii")


class UpdateLocationView(LoginRequiredMixin, UpdateView):
    model = Location
    fields = ["city", "country"]
    template_name = "aplicatie1/locations_form.html"

    def get_success_url(self):
        return reverse("locations:lista_locatii")


@login_required
def delete_location(request, pk):
    location_value = Location.objects.get(id=pk)
    AuditLocation.objects.create(
        location=location_value.id,
        city=location_value.city,
        country=location_value.country,
        active=location_value.active,
        user_id=request.user.id,
    )
    Location.objects.filter(id=pk).delete()
    return redirect(f'/locations/?page={request.GET.get("page")}')


@login_required
def deactivate_location(request, pk):
    Location.objects.filter(id=pk).update(active=0)
    return redirect(f'/locations/?page={request.GET.get("page")}')


@login_required
def activate_location(request, pk):
    Location.objects.filter(id=pk).update(active=1)
    return redirect(f'/locations/?page={request.GET.get("page")}')


class CompanyView(LoginRequiredMixin, ListView):
    model = Company
    template_name = "aplicatie1/company_index.html"
    paginate_by = 5
    queryset = model.objects.all().order_by("id")

    def get_context_data(self, *args, **kwargs):
        data = super().get_context_data()
        data["page"] = (
            self.request.GET.get("page") if self.request.GET.get("page") else 1
        )
        return data


class CreateCompanyView(LoginRequiredMixin, CreateView):
    model = Company
    fields = ["name", "website", "location"]
    template_name = "aplicatie1/company_form.html"

    def get_success_url(self):
        return reverse("locations:list_companies")


class UpdateCompanyView(LoginRequiredMixin, UpdateView):
    model = Company
    fields = ["name", "website", "location"]
    template_name = "aplicatie1/company_form.html"

    def get_success_url(self):
        return reverse("locations:list_companies")


@login_required
def delete_company(request, pk):
    company_value = Location.objects.get(id=pk)
    AuditCompany.objects.create(
        company=company_value.id,
        name=company_value.name,
        website=company_value.website,
        location=company_value.location,
        active=company_value.active,
        user_id=request.user.id,
    )
    Company.objects.filter(id=pk).delete()
    return redirect(f"/locations/companies/")


@login_required
def deactivate_company(request, pk):
    Company.objects.filter(id=pk).update(active=0)
    return redirect(f"/locations/companies/")


@login_required
def activate_company(request, pk):
    Company.objects.filter(id=pk).update(active=1)
    return redirect(f"/locations/companies/")

Week5/class/proiect/templates/aplicatie1/company_form.html
{% extends 'base.html' %}
{% block content %}
    <form method="POST">
        {% csrf_token %}
    {% for field in form %}
        {{ field.label }} {{ field }} {{ field.errors }}
    {% endfor %}
    <button type="submit" class="btn btn-success">Salveaza</button>
    </form>
{% endblock %}

Week5/class/proiect/templates/aplicatie1/company_index.html
{% extends 'base.html' %}
{% block content %}
    <a class="btn btn-primary" href="{% url 'locations:add_company' %}">Adaugare companie</a>
    <table class="table">
    <thead>
    <tr>
        <th>Index</th>
        <th>Name</th>
        <th>Website</th>
        <th>Location</th>
        <th>State</th>
        <th>Actions</th>
    </tr>
    </thead>
    <tbody>
    {% for item in company_list %}
        <tr>
        <td>{{ forloop.counter }}</td>
        <td>{{ item.name }}</td>
        <td>{{ item.website }}</td>
        <td>{{ item.location.city }}</td>
        <td>{% if item.active is True %}
            Active
            {% else %}
            Inactive
            {% endif %}</td>
        <td><a class="btn btn-success" href="{% url 'locations:update_company' item.id %}">Edit</a>
            <a class="btn btn-danger" href="{% url 'locations:delete_company' item.id %}?page={{ page }}">Delete</a>
            {% if item.active is True %}
                <a class="btn btn-info" href="{% url 'locations:deactivate_company' item.id %}?page={{ page }}">Deactivate</a>
            {% else %}
                 <a class="btn btn-success" href="{% url 'locations:activate_company' item.id %}?page={{ page }}">Activate</a>
            {% endif %}
        </td>
        </tr>
    {% endfor %}
    </tbody>
    </table>
    <div class="d-flex align-items-center">
        {% if is_paginated %}
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li><a class="btn" href="?page={{ page_obj.previous_page_number }}"><<</a></li>
                {% else %}
                    <li class="disabled btn"><span><<</span></li>
                {% endif %}
                {% for i in paginator.page_range %}
                    {% if page_obj.number == i %}
                        <li class="active btn btn-info"><span>{{ i }}<span class="sr-only">(curent)</span></span></li>
                    {% else %}
                        <li><a class="btn" href="?page={{ i }}">{{ i }}</a></li>
                    {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                    <li><a class="btn" href="?page={{ page_obj.next_page_number }}">>></a></li>
                {% else %}
                    <li class="disabled btn"><span>>></span></li>
                {% endif %}
            <span class="align-right">Showing {{ page_obj.start_index }} - {{ page_obj.end_index }} of {{ page_obj.paginator.count }}</span>
            </ul>
        {% endif %}
    </div>
{% endblock %}

Week5/class/proiect/templates/aplicatie1/locations_form.html
{% extends 'base.html' %}
{% block content %}
    <form method="POST">
        {% csrf_token %}
    {% for field in form %}
        {{ field.label }} {{ field }} {{ field.errors }}
    {% endfor %}
    <button type="submit" class="btn btn-success">Salveaza</button>
    </form>
{% endblock %}

Week5/class/proiect/templates/aplicatie1/locations_index.html
{% extends 'base.html' %}
{% block content %}
    <a class="btn btn-primary" href="{% url 'locations:adauga' %}">Adaugare locatii</a>
    <table class="table">
    <thead>
    <tr>
        <th>Index</th>
        <th>City</th>
        <th>Country</th>
        <th>State</th>
        <th>Actions</th>
    </tr>
    </thead>
    <tbody>
    {% for item in location_list %}
        <tr>
        <td>{{ forloop.counter }}</td>
        <td>{{ item.city }}</td>
        <td>{{ item.country }}</td>
        <td>{% if item.active is True %}
            Active
            {% else %}
            Inactive
            {% endif %}</td>
        <td><a class="btn btn-success" href="{% url 'locations:modifica' item.id %}">Edit</a>
            <a class="btn btn-danger" href="{% url 'locations:sterge' item.id %}?page={{ page }}">Delete</a>
            {% if item.active is True %}
                <a class="btn btn-info" href="{% url 'locations:dezactiveaza' item.id %}?page={{ page }}">Deactivate</a>
            {% else %}
                 <a class="btn btn-success" href="{% url 'locations:activeaza' item.id %}?page={{ page }}">Activate</a>
            {% endif %}
        </td>
        </tr>
    {% endfor %}
    </tbody>
    </table>
    <div class="d-flex align-items-center">
        {% if is_paginated %}
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li><a class="btn" href="?page={{ page_obj.previous_page_number }}"><<</a></li>
                {% else %}
                    <li class="disabled btn"><span><<</span></li>
                {% endif %}
                {% for i in paginator.page_range %}
                    {% if page_obj.number == i %}
                        <li class="active btn btn-info"><span>{{ i }}<span class="sr-only">(curent)</span></span></li>
                    {% else %}
                        <li><a class="btn" href="?page={{ i }}">{{ i }}</a></li>
                    {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                    <li><a class="btn" href="?page={{ page_obj.next_page_number }}">>></a></li>
                {% else %}
                    <li class="disabled btn"><span>>></span></li>
                {% endif %}
            <span class="align-right">Showing {{ page_obj.start_index }} - {{ page_obj.end_index }} of {{ page_obj.paginator.count }}</span>
            </ul>
        {% endif %}
    </div>
{% endblock %}